<?php

// Data functions (insert, update, delete, form) for table Teachers_Table

// This script and data application were generated by AppGini 5.81
// Download AppGini for free from https://bigprof.com/appgini/download/

function Teachers_Table_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Teachers_Table');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Email_id'] = $_REQUEST['Email_id'];
		if($data['Email_id'] == empty_lookup_value) { $data['Email_id'] = ''; }
	$data['Ph_number'] = $_REQUEST['Ph_number'];
		if($data['Ph_number'] == empty_lookup_value) { $data['Ph_number'] = ''; }

	// hook: Teachers_Table_before_insert
	if(function_exists('Teachers_Table_before_insert')) {
		$args = array();
		if(!Teachers_Table_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Teachers_Table', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Teachers_Table_after_insert
	if(function_exists('Teachers_Table_after_insert')) {
		$res = sql("select * from `Teachers_Table` where `Name`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Teachers_Table_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Teachers_Table', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Teachers_Table_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Teachers_Table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// copy Teachers_Table
	$res = sql("SELECT * FROM `Teachers_Table` WHERE `Ph_number`='{$safe_sid}'", $eo);
	while($row = db_fetch_assoc($res)) {
		$data = array(
			'SelectedID' => $row['Name'],
			'Email_id' => $row['Email_id'],
			'Ph_number' => $destination_id,
		);

		$ch = curl_insert_handler('Teachers_Table', $data);
		if($ch !== false) $requests[] = $ch;
	}

	// launch requests, asynchronously
	curl_batch($requests);
}

function Teachers_Table_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Teachers_Table');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Teachers_Table' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Teachers_Table' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Teachers_Table_before_delete
	if(function_exists('Teachers_Table_before_delete')) {
		$args=array();
		if(!Teachers_Table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Teachers_Table
	$res = sql("select `Name` from `Teachers_Table` where `Name`='$selected_id'", $eo);
	$Name = db_fetch_row($res);
	$rires = sql("select count(1) from `Teachers_Table` where `Ph_number`='".addslashes($Name[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Teachers_Table", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Teachers_Table", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Teachers_Table_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Teachers_Table_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `Teachers_Table` where `Name`='$selected_id'", $eo);

	// hook: Teachers_Table_after_delete
	if(function_exists('Teachers_Table_after_delete')) {
		$args=array();
		Teachers_Table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Teachers_Table' and pkValue='$selected_id'", $eo);
}

function Teachers_Table_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Teachers_Table');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Teachers_Table' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Teachers_Table' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Email_id'] = makeSafe($_REQUEST['Email_id']);
		if($data['Email_id'] == empty_lookup_value) { $data['Email_id'] = ''; }
	$data['Ph_number'] = makeSafe($_REQUEST['Ph_number']);
		if($data['Ph_number'] == empty_lookup_value) { $data['Ph_number'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Teachers_Table_before_update
	if(function_exists('Teachers_Table_before_update')) {
		$args = array();
		if(!Teachers_Table_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Teachers_Table` set       `Email_id`=' . (($data['Email_id'] !== '' && $data['Email_id'] !== NULL) ? "'{$data['Email_id']}'" : 'NULL') . ', `Ph_number`=' . (($data['Ph_number'] !== '' && $data['Ph_number'] !== NULL) ? "'{$data['Ph_number']}'" : 'NULL') . " where `Name`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Teachers_Table_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Teachers_Table_after_update
	if(function_exists('Teachers_Table_after_update')) {
		$res = sql("SELECT * FROM `Teachers_Table` WHERE `Name`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['Name'];
		$args = array();
		if(!Teachers_Table_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Teachers_Table' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Teachers_Table_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Teachers_Table');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_Ph_number = thisOr(undo_magic_quotes($_REQUEST['filterer_Ph_number']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Ph_number
	$combo_Ph_number = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Teachers_Table' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Teachers_Table' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Teachers_Table` WHERE `Name`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Teachers_Table_view.php', false);
		}
		$combo_Ph_number->SelectedData = $row['Ph_number'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_Ph_number->SelectedData = $filterer_Ph_number;
	}
	$combo_Ph_number->HTML = '<span id="Ph_number-container' . $rnd1 . '"></span><input type="hidden" name="Ph_number" id="Ph_number' . $rnd1 . '" value="' . html_attr($combo_Ph_number->SelectedData) . '">';
	$combo_Ph_number->MatchText = '<span id="Ph_number-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Ph_number" id="Ph_number' . $rnd1 . '" value="' . html_attr($combo_Ph_number->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Ph_number__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Ph_number'] : $filterer_Ph_number); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Ph_number_reload__RAND__) == 'function') Ph_number_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Ph_number_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Ph_number-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Ph_number__RAND__.value, t: 'Teachers_Table', f: 'Ph_number' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Ph_number"]').val(resp.results[0].id);
							$j('[id=Ph_number-container-readonly__RAND__]').html('<span id="Ph_number-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_Table_view_parent]').hide(); }else{ $j('.btn[id=Teachers_Table_view_parent]').show(); }


							if(typeof(Ph_number_update_autofills__RAND__) == 'function') Ph_number_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'Teachers_Table', f: 'Ph_number' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_Ph_number__RAND__.value = e.added.id;
				AppGini.current_Ph_number__RAND__.text = e.added.text;
				$j('[name="Ph_number"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_Table_view_parent]').hide(); }else{ $j('.btn[id=Teachers_Table_view_parent]').show(); }


				if(typeof(Ph_number_update_autofills__RAND__) == 'function') Ph_number_update_autofills__RAND__();
			});

			if(!$j("#Ph_number-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Ph_number__RAND__.value, t: 'Teachers_Table', f: 'Ph_number' },
					success: function(resp) {
						$j('[name="Ph_number"]').val(resp.results[0].id);
						$j('[id=Ph_number-container-readonly__RAND__]').html('<span id="Ph_number-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_Table_view_parent]').hide(); }else{ $j('.btn[id=Teachers_Table_view_parent]').show(); }

						if(typeof(Ph_number_update_autofills__RAND__) == 'function') Ph_number_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Ph_number__RAND__.value, t: 'Teachers_Table', f: 'Ph_number' },
				success: function(resp) {
					$j('[id=Ph_number-container__RAND__], [id=Ph_number-container-readonly__RAND__]').html('<span id="Ph_number-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Teachers_Table_view_parent]').hide(); }else{ $j('.btn[id=Teachers_Table_view_parent]').show(); }

					if(typeof(Ph_number_update_autofills__RAND__) == 'function') Ph_number_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Teachers_Table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Teachers_Table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Teachers Table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Teachers_Table_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Teachers_Table_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Teachers_Table_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Email_id').replaceWith('<div class=\"form-control-static\" id=\"Email_id\">' + (jQuery('#Email_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Ph_number').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Ph_number_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Ph_number)%%>', $combo_Ph_number->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Ph_number)%%>', $combo_Ph_number->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Ph_number)%%>', urlencode($combo_Ph_number->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('Ph_number' => array('Teachers_Table', 'Ph number'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(Name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Email_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ph_number)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', safe_html($urow['Name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', html_attr($row['Name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode($urow['Name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Email_id)%%>', safe_html($urow['Email_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Email_id)%%>', html_attr($row['Email_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Email_id)%%>', urlencode($urow['Email_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Ph_number)%%>', safe_html($urow['Ph_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Ph_number)%%>', html_attr($row['Ph_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ph_number)%%>', urlencode($urow['Ph_number']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(Name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Email_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Email_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ph_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ph_number)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Teachers_Table');
	if($selected_id) {
		$jdata = get_joined_record('Teachers_Table', $selected_id);
		if($jdata === false) $jdata = get_defaults('Teachers_Table');
		$rdata = $row;
	}
	$templateCode .= loadView('Teachers_Table-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Teachers_Table_dv
	if(function_exists('Teachers_Table_dv')) {
		$args=array();
		Teachers_Table_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>